### ISSUE TITLE
[Proposal] Component Theme Change( 组件主题切换 )

### ISSUE THREAD

**Issue by json-sun** [apache/incubator-weex-ui#216]
🎨 Enrich the color of components and enhance the usability of components in the business side.

## Background

- Different companies have different themes for product design, most of the app's primary color are not the same.
- Currently `weex-ui` only can define component colors through parameter configuration.
- Using props to define the color of a component increases the use of useless code.

## Purpose

Developer can change the primary color through some configuration. *Less Code.*

#### ~~Plan 1:  Use CSS extension language~~

In some Vue.js component libraries, use CSS extension language to build colorful components is a good way.🤔 ( e.g. [ElementUI](https://github.com/ElemeFE/element) )

But `Weex` is not support global css, component can only get style through import the corresponding .css file. However, Weex component usually use dynamic style to bind styles ( use css in js ). 😢

#### Plan 2: Js theme file build in

We hope can import the required theme files when babel parsing the specific .vue file.

About the implementation method, we can make some changes based on the [babel-plugin-componnet](https://github.com/ElementUI/babel-plugin-component).

So, get [babel-plugin-weexcomponent](https://github.com/Yanjiie/babel-plugin-weexcomponent).

We can use a configuration like this in `.babelrc` :
```javascript
{
  "presets": [ "es2015", "stage-0" ],
  "plugins": [
    [
      "weexcomponent",      // babel plugin name
      {
        "style": false,
        "libraryName": "weex-ui",
        "libDir": "packages",
        "themeDir": "lib/theme",    // theme lib path
        "themeConfig": {
          "name": "default"         // theme name, default is 'default'. Try to use 'yellow' replace it to have a test !
        }
      }
    ]
  ]
}
```

## Theme files directory structure
```
- root
  - lib
    - theme                       // theme files root directory
      - default                   // default theme directory
        - index.js                // common style
        - componentA.js           // component style
        - componentB.js           // component style
      - blue                      //  other theme ...
        - index.js
        - componentA.js
        - componentB.js
  - packages
    - componentA
      - index.js
    - componentB
      - index.js
```

Can use these files like this: 

e.g. Use blue theme

```javascript
// component.vue
import STYLE from 'weex-ui/lib/theme/default/index.js';
```
will convert to

```javascript
// component.vue
import STYLE from 'weex-ui/lib/theme/blue/index.js';
```

## Progress

**2018.04.04 Update:**

These components already support theme change currently:
- `wxc-minibar`
- `wxc-searchbar`
- `wxc-radio`
- `wxc-checkbox`
- `wxc-simple-flow`
- `wxc-slider-bar`
- `wxc-grid-select`
- `wxc-page-calendar`

If you have a good idea💡, welcome to discuss it here! 🤗

**Comment by tw93** [comment]
Good Work!
Currently, the component is modifying  color through parameter configuration, but most of the app's primary color are not the same, and it is convenient for developers to configure the `.babelrc` .

**Comment by vanpipy** [comment]
Hey @Yanjiie , I try to use babel-plugin-weexcomponent to switch the theme but nothing different display.

So some questions here I want to ask:

1. What is the format of file like `weex-ui/lib/theme/blue/index.js`
2. Why the file suffix should be `.js` not the `.less` or `.css`

The answer for quersion 2 maybe something about `<style scoped>`?

Could you give something more detail example to display the way to use?

Thank your time :D.

**Comment by Yanjiie** [comment]
Right!👍 That's also in our plan. We will support custom style file in the future. @vanpipy

**Comment by yinianjiqi** [comment]
当与其他组件一排的时候searchbar会溢出，应该怎么修改？
