### ISSUE TITLE
wxc-tab-bar iphoneX系列兼容问题

### ISSUE THREAD

**Issue by franksun1988** [apache/incubator-weex-ui#485]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
iphone x

下巴兼容高度问题
paddingBottom:isIPhoneX?'78px':'0'

##### 2.Expected behavior and actual behavior.   
 我觉得换算后的高度应该是68px

**Comment by tw93** [comment]
特意高一点点，原有的padding
