### ISSUE TITLE
android下loading动画无效

### ISSUE THREAD

**Issue by sq5779261314** [apache/incubator-weex-ui#487]
wxc-loading在android下不显示加载动画

**Comment by tw93** [comment]
请参考这个https://apache.github.io/incubator-weex-ui/#/cn/faq?id=gif-%e5%9b%be%e7%89%87%e5%9c%a8-android-%e4%b8%8a%e9%9d%a2%e6%b2%a1%e6%9c%89%e5%8a%a8%e7%94%bb
