### ISSUE TITLE
wxc-lightbox prop show-indicator didn't work

### ISSUE THREAD

**Issue by alexyoubaifu** [apache/incubator-weex-ui#491]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex

##### 2.Expected behavior and actual behavior.   
 - expect `wxc-lightbox` prop `show-indicator` to hide indicator
 - actual: `show-indicator` didn't work, and I looked up the [source code](https://github.com/apache/incubator-weex-ui/blob/master/packages/wxc-lightbox/index.vue), found I have to use `indicatorColor` do something like this `:indicatorColor="{ width: 0 + 'px' }"` to hide the indicator

##### 3.Steps to reproduce the problem.    
 - import wxc-lightbox and specify the `show-indicator` to `true`

**Comment by tw93** [comment]
you need use `:show-indicator="true"`，You can see it's showing

![image](https://user-images.githubusercontent.com/8736212/74102794-e00c7a80-4b81-11ea-86a4-454ebd727964.png)

**Comment by tw93** [comment]
I'm sorry that I forgot to add it. Now the latest version has been added, please update to the latest version 0.8.4
