### ISSUE TITLE
wxc-lightbox prop show-indicator didn't work

### ISSUE THREAD

**Issue by alexyoubaifu** [apache/incubator-weex-ui#493]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex

##### 2.Expected behavior and actual behavior.   
same issue from https://github.com/apache/incubator-weex-ui/issues/491
 - expect `wxc-lightbox` prop `show-indicator` to hide indicator
 - actual: `show-indicator` didn't work, and I looked up the [source code](https://github.com/apache/incubator-weex-ui/blob/master/packages/wxc-lightbox/index.vue), found I have to use `indicatorColor` do something like this `:indicatorColor="{ width: 0 + 'px' }"` to hide the indicator
- look at the source code, there's no place use `show-indicator`

##### 3.Steps to reproduce the problem.    
 - import wxc-lightbox and specify the `show-indicator` to `false`
- `:show-indicator="false"`
 
### screenshot:
![截圖 2020-02-10 上午9 57 34](https://user-images.githubusercontent.com/57611569/74115836-e8010480-4beb-11ea-919e-d53932dbdef6.png)

**Comment by tw93** [comment]
I'm sorry that I forgot to add it. Now the latest version has been added, please update to the latest version 0.8.4
