### ISSUE TITLE
wxc-searchbar的bar-style要怎么设置

### ISSUE THREAD

**Issue by EdifierX** [apache/incubator-weex-ui#494]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - eeui  weex

##### 2.Expected behavior and actual behavior.   
 - wxc-searchbar的bar-style有使用样例吗，请问如何设置圆角，宽高？
 - wxc-searchbar‘s bar style has a sample, how to set the fillet, width and height?

**Comment by tw93** [comment]
参考一下这个，https://github.com/apache/incubator-weex-ui/blob/master/example/ep-slider/index.vue#L29
https://github.com/apache/incubator-weex-ui/blob/master/example/ep-slider/index.vue#L162
一样的写法
