### ISSUE TITLE
web端渲染时提示TypeError: _vm._px2rem is not a function 但是native端可以正常渲染

### ISSUE THREAD

**Issue by myhighland** [apache/incubator-weex-ui#500]
开发环境如下：
2.0.0-beta.31 (Core 2.0.0-beta.31)
- @weex-cli/generator : v2.0.0-beta.16
- @weex-cli/debug : v2.0.0-beta.31
- @weex-cli/compile : v2.0.0-beta.27
- @weex-cli/build : v2.0.0-beta.15
- @weex-cli/doctor : v2.0.0-beta.20
- @weex-cli/run : v2.0.0-beta.21
- @weex-cli/device : v2.0.0-beta.2

只是web端的渲染有问题

**Comment by cnryb** [comment]
要不来个最小可复现的demo看看？

**Comment by tw93** [comment]
没有回复，暂时关闭，此问题应该是和toolkit的版本以及 weex-vue-render 版本 打包相关的东西有关系
