### ISSUE TITLE
wxc-ep-slider 禁用滑动

### ISSUE THREAD

**Issue by z1900** [apache/incubator-weex-ui#508]
##### 1.Your development environment（weex、weex-toolkit、system and more).    
 - weex
 - android 10.0.0

##### 2.Expected behavior and actual behavior.   
 - 期望可以有禁止滑动的属性
 - 目前文档没有该属性，在源码中看到有enableSwipe属性，但是实际并未使用

**Comment by tw93** [comment]
已增加支持，可见 https://github.com/apache/incubator-weex-ui/releases/tag/v0.8.6
